[Mail]
Server = "whatev@gmail.com"
Port = 993
Username = "no"
Password = "secret"

[Synchro]
Key = "apiKey"

[[Rules]]
Sender = "yeet@gmail.com"
Blocked = [ "block this pantsgrab" ]
Bllowed = [ "yeet", "yeet harder" ]

[[Rules]]
Address = "urmum@gmail.com"
Blocked = [ "block this grabpants" ]
Allowed = []
