Server = "whatev@gmail.com"
Port = 993
Username = "no"
Password = "secret"

[[rules]]
Sender = "yeet@gmail.com"
Blocked = [ "block this pantsgrab" ]
Bllowed = [ "yeet", "yeet harder" ]

[[rules]]
Address = "urmum@gmail.com"
Blocked = [ "block this grabpants" ]
Allowed = []
